"""
UPSS PowerPoint Report Tool

Generate PowerPoint reports.
"""

from __future__ import annotations

from pathlib import Path

from pptx import Presentation

from tools.base_tool import BaseTool
from tools.tool_context import ToolContext
from tools.tool_permission import ToolPermission
from tools.tool_result import ToolResult
from tools.tool_schema import (
    ToolCategory,
    ToolMetadata,
)

from tools.report_tools.schemas import (
    PPTReportRequest,
    ReportResponse,
)


class PPTReportTool(BaseTool):
    """
    Generate PowerPoint reports.
    """

    metadata = ToolMetadata(

        name="report.powerpoint",

        display_name="PowerPoint Report",

        description="Generate PowerPoint presentations.",

        category=ToolCategory.PRODUCTIVITY,

        tags=[
            "report",
            "powerpoint",
            "presentation",
            "ppt",
        ],

    )

    permission = ToolPermission.read_only()

    input_model = PPTReportRequest

    async def execute(
        self,
        context: ToolContext,
        request: PPTReportRequest,
    ) -> ToolResult:

        output_path = Path(
            request.output_path
        )

        output_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        presentation = Presentation()

        #
        # Title Slide
        #

        title_layout = presentation.slide_layouts[0]

        slide = presentation.slides.add_slide(
            title_layout
        )

        slide.shapes.title.text = request.title

        slide.placeholders[1].text = (
            "Generated by UPSS"
        )

        #
        # Content Slides
        #

        content_layout = presentation.slide_layouts[1]

        for item in request.slides:

            slide = presentation.slides.add_slide(
                content_layout
            )

            title = item.get(
                "title",
                "Untitled",
            )

            content = item.get(
                "content",
                "",
            )

            slide.shapes.title.text = title

            slide.placeholders[1].text = content

        presentation.save(
            output_path
        )

        response = ReportResponse(

            success=True,

            message="PowerPoint report generated successfully.",

            output_path=str(
                output_path.resolve()
            ),

        )

        return ToolResult.ok(

            message=response.message,

            data=response.model_dump(),

        )