"""
Planner Schemas

Shared schemas used by:

- Planner
- Workflow Engine
- Tool Selection Engine
- Execution Controller
"""

from __future__ import annotations

from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field


# ==========================================================
# Planning Context
# ==========================================================

class PlanningContext(BaseModel):
    """
    Input received by the Planner.
    """

    query: str

    domain: str

    user_id: Optional[int] = None

    conversation_id: Optional[int] = None

    memory: List[Dict[str, Any]] = Field(
        default_factory=list
    )

    preferences: Dict[str, Any] = Field(
        default_factory=dict
    )

    metadata: Dict[str, Any] = Field(
        default_factory=dict
    )


# ==========================================================
# Planner Task
# ==========================================================

class PlannerTask(BaseModel):
    """
    One executable task inside a plan.
    """

    id: str

    name: str

    description: str

    tool: Optional[str] = None

    agent: Optional[str] = None

    parameters: Dict[str, Any] = Field(
        default_factory=dict
    )

    depends_on: List[str] = Field(
        default_factory=list
    )

    estimated_duration: Optional[float] = None

    requires_human: bool = False

    retryable: bool = True

    priority: int = 1


# ==========================================================
# Execution Plan
# ==========================================================

class ExecutionPlan(BaseModel):
    """
    Final output generated by the Planner.
    """

    goal: str

    domain: str

    complexity: str = "simple"

    risk: str = "low"

    estimated_cost: float = 0.0

    estimated_duration: Optional[float] = None

    tasks: List[PlannerTask] = Field(
        default_factory=list
    )


# ==========================================================
# Planner Result
# ==========================================================

class PlannerResult(BaseModel):
    """
    Response returned by Planner.
    """

    success: bool

    message: str

    execution_plan: ExecutionPlan